# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='location',
        ),
    ]
