# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('office_address', models.CharField(max_length=255)),
                ('office_city', models.CharField(max_length=255)),
                ('office_state', models.CharField(max_length=255)),
                ('office_zip', models.CharField(max_length=255)),
                ('city_hall_phone', models.CharField(max_length=255)),
                ('city_hall_address', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('bio', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
