# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0002_remove_cause_image'),
        ('politician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='causes',
            field=models.ManyToManyField(blank=True, to='cause.Cause'),
        ),
    ]
