# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0002_politician_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='causes',
        ),
    ]
