# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_body', '0003_remove_legislativebody_politicians'),
        ('politician', '0003_remove_politician_causes'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='legislative_body',
            field=models.ManyToManyField(blank=True, to='legislative_body.LegislativeBody'),
        ),
    ]
