# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0004_politician_legislative_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
