# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0001_initial'),
        ('legislative_body', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativebody',
            name='politicians',
            field=models.ManyToManyField(blank=True, to='politician.Politician'),
        ),
    ]
