# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_body', '0002_legislativebody_politicians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativebody',
            name='politicians',
        ),
    ]
