# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_legislative_body'),
        ('legislative_body', '0003_remove_legislativebody_politicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativebody',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.Event'),
        ),
    ]
