# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('prefix', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs'), ('Mr.', 'Mr.')], max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('bio', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
