# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160901_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
