# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(null=True, upload_to=b'')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('frequency_of_notifications', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=255)),
                ('modified', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('causes', models.ManyToManyField(blank=True, related_name='causes_subscribed_to', to='member.Member')),
                ('key_members', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_key_member', to='member.Member')),
                ('moderators', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_moderator', to='member.Member')),
            ],
        ),
    ]
