# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='frequency_of_notifications',
        ),
    ]
