# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0002_remove_cause_frequency_of_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='causes',
            field=models.ManyToManyField(null=True, related_name='causes_subscribed_to', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='key_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_key_member', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='moderators',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_moderator', to='member.Member'),
        ),
    ]
