# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0003_remove_politician_causes'),
        ('cause', '0002_remove_cause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='politicians',
            field=models.ManyToManyField(blank=True, to='politician.Politician'),
        ),
    ]
