# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('cause', '0005_auto_20160804_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='key_members',
        ),
        migrations.AddField(
            model_name='cause',
            name='key_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_key_member', to='member.Member'),
        ),
        migrations.RemoveField(
            model_name='cause',
            name='members',
        ),
        migrations.AddField(
            model_name='cause',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_member', to='member.Member'),
        ),
        migrations.RemoveField(
            model_name='cause',
            name='moderators',
        ),
        migrations.AddField(
            model_name='cause',
            name='moderators',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause_moderator', to='member.Member'),
        ),
    ]
