# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(editable=False)),
                ('modified_on', models.DateTimeField()),
                ('verified_on', models.BooleanField(default=False)),
            ],
        ),
    ]
