# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
