# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_body', '0001_initial'),
        ('event', '0002_auto_20160831_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='leg_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislative_body.LegislativeBody'),
        ),
    ]
