# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative_body', '0001_initial'),
        ('event', '0004_remove_event_leg_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='legislative_body.LegislativeBody'),
        ),
    ]
