# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, to='legislative_body.LegislativeBody'),
        ),
    ]
