# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20160901_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events',
            new_name='legislative_body',
        ),
    ]
