# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20160901_0218'),
        ('event', '0008_remove_event_legislative_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='notification.Notification'),
        ),
    ]
